export default [
    {"description":"Energia elétrica",      "amount":"150.55","type":"saída","frequency":"recorrente","date":"2021-1-10"},
    {"description":"Água",                  "amount":"75.55", "type":"saída","frequency":"recorrente","date":"2022-1-15"},
    {"description": "Telefone",             "amount":"99.99", "type":"saída","frequency":"recorrente","date":"2022-1-23"},
    {"description":"Plano de Saúde",        "amount":"300.00","type":"saída","frequency":"recorrente","date":"2022-1-23"},
    {"description":"Compras do mês",        "amount":"625.78","type":"saída","frequency":"recorrente","date":"2022-1-23"},
    {"description":"Lanche",                "amount":"45.70", "type":"saída","frequency":"eventual",  "date":"2022-1-23"},
    {"description":"Blusa",                 "amount":"95.70", "type":"saída","frequency":"eventual",  "date":"2022-1-23"},
    {"description":"Energia elétrica",      "amount":"125.55","type":"saída","frequency":"recorrente","date":"2022-2-10"},
    {"description":"Água",                  "amount":"90.15", "type":"saída","frequency":"recorrente","date":"2022-2-15"},
    {"description":"Telefone",              "amount":"99.99", "type":"saída","frequency":"recorrente","date":"2022-2-23"},
    {"description":"Plano de Saúde",        "amount":"300.00","type":"saída","frequency":"recorrente","date":"2022-2-23"},
    {"description":"Compras do mês",        "amount":"540.00","type":"saída","frequency":"recorrente","date":"2022-2-25"},
    {"description":"Parcela do Celular 1/5","amount":"150.99","type":"saída","frequency":"eventual",  "date":"2022-2-26"},
    {"description":"Cinema",                "amount":"45.00", "type":"saída","frequency":"eventual",  "date":"2022-2-23"},
    {"description":"Energia elétrica",      "amount":"97.00", "type":"saída","frequency":"recorrente","date":"2022-3-10"},
    {"description":"Água",                  "amount":"100.10","type":"saída","frequency":"recorrente","date":"2022-3-15"},
    {"description":"Telefone",              "amount":"99.99", "type":"saída","frequency":"recorrente","date":"2022-3-23"},
    {"description":"Plano de Saúde",        "amount":"300.00","type":"saída","frequency":"recorrente","date":"2022-3-23"},
    {"description":"Compras do mês",        "amount":"800.50","type":"saída","frequency":"recorrente","date":"2022-3-17"},
    {"description":"Parcela do Celular 2/5","amount":"150.99","type":"saída","frequency":"eventual",  "date":"2022-3-18"},
    {"description":"Troca de Oléo do carro","amount":"90.00", "type":"saída","frequency":"eventual",  "date":"2022-3-23"},
    {"description":"Energia elétrica",      "amount":"75.99", "type":"saída","frequency":"recorrente","date":"2022-4-10"},
    {"description":"Água",                  "amount":"80.33", "type":"saída","frequency":"recorrente","date":"2022-4-15"},
    {"description":"Telefone",              "amount":"99.99", "type":"saída","frequency":"recorrente","date":"2022-4-23"},
    {"description":"Plano de Saúde",        "amount":"300.00","type":"saída","frequency":"recorrente","date":"2022-4-23"},
    {"description":"Compras do mês",        "amount":"600.00","type":"saída","frequency":"recorrente","date":"2022-4-25"},
    {"description":"Parcela do Celular 3/5","amount":"150.99","type":"saída","frequency":"eventual",  "date":"2022-4-26"},
    {"description":"Ebook de React Js",     "amount":"85.95", "type":"saída","frequency":"eventual",  "date":"2022-4-13"},
    {"description":"Energia elétrica",      "amount":"125.55","type":"saída","frequency":"recorrente","date":"2022-5-10"},
    {"description":"Água",                  "amount":"90.15", "type":"saída","frequency":"recorrente","date":"2022-5-15"},
    {"description":"Telefone",              "amount":"99.99", "type":"saída","frequency":"recorrente","date":"2022-5-23"},
    {"description":"Plano de Saúde",        "amount":"300.00","type":"saída","frequency":"recorrente","date":"2022-5-23"},
    {"description":"Compras do mês",        "amount":"540.00","type":"saída","frequency":"recorrente","date":"2022-5-25"},
    {"description":"Parcela do Celular 4/5","amount":"150.99","type":"saída","frequency":"eventual",  "date":"2022-5-26"},
    {"description":"Blusa Iron Man",        "amount":"150.00","type":"saída","frequency":"eventual",  "date":"2022-1-23"},
    {"description":"Energia elétrica",      "amount":"200.00","type":"saída","frequency":"recorrente","date":"2022-6-10"},
    {"description":"Água",                  "amount":"150.00","type":"saída","frequency":"recorrente","date":"2022-6-15"},
    {"description":"Telefone",              "amount":"99.99", "type":"saída","frequency":"recorrente","date":"2022-6-23"},
    {"description":"Plano de Saúde",        "amount":"300.00","type":"saída","frequency":"recorrente","date":"2022-6-23"},
    {"description":"Compras do mês",        "amount":"559.15","type":"saída","frequency":"recorrente","date":"2022-6-25"},
    {"description":"Parcela do Celular 5/5","amount":"150.99","type":"saída","frequency":"eventual",  "date":"2022-6-26"},
    {"description":"Perfume",               "amount":"250.00","type":"saída","frequency":"eventual",  "date":"2022-6-21"},
    {"description":"Energia elétrica",      "amount":"250.00","type":"saída","frequency":"recorrente","date":"2022-7-10"},
    {"description":"Água",                  "amount":"90.00", "type":"saída","frequency":"recorrente","date":"2022-7-15"},
    {"description":"Telefone",              "amount":"99.99", "type":"saída","frequency":"recorrente","date":"2022-7-23"},
    {"description":"Plano de Saúde",        "amount":"300.00","type":"saída","frequency":"recorrente","date":"2022-7-23"},
    {"description":"Compras do mês",        "amount":"700.00","type":"saída","frequency":"recorrente","date":"2022-7-25"},
    {"description":"Cafeteira",             "amount":"250.00","type":"saída","frequency":"eventual",  "date":"2022-7-26"},
    {"description":"Pizza",                 "amount":"60.00", "type":"saída","frequency":"eventual",  "date":"2022-7-19"}
  ]